//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssueReturn
    {
        public int BookIssueReturnId { get; set; }
        public int MemberId { get; set; }
        public Nullable<int> AssesionId { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> LateDays { get; set; }
        public string FineAmount { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> MemberCategoryId { get; set; }
        public string Remarks { get; set; }
    
        public virtual AssesionMapping AssesionMapping { get; set; }
        public virtual Member Member { get; set; }
        public virtual MemberCategory MemberCategory { get; set; }
    }
}
